{
  "formatVersion": "1.1",
  "component": {
    "group": "org.prunes",
    "module": "transceiver",
    "version": "0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "transceiver-0.1-SNAPSHOT.jar",
          "url": "transceiver-0.1-SNAPSHOT.jar",
          "size": 16773,
          "sha512": "a56a66f16e62cdc240a71c74d74f27415b0f026c9b0dc645e1c4b9d8a52b16737c35d7c8f44cc5f3c0cab13dc025e8cbf53e8fb629205d026a6d4dc73a0f44ad",
          "sha256": "af9541f820f40257fda18c973ccf8c8892ab042e3a006f94ad55d2ce23301cd0",
          "sha1": "cdb9043f3adcc5cd7e1fc42c7d8d54d5238a247d",
          "md5": "547425d9bf7b62278b362df02ca6519c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.35"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "transceiver-0.1-SNAPSHOT.jar",
          "url": "transceiver-0.1-SNAPSHOT.jar",
          "size": 16773,
          "sha512": "a56a66f16e62cdc240a71c74d74f27415b0f026c9b0dc645e1c4b9d8a52b16737c35d7c8f44cc5f3c0cab13dc025e8cbf53e8fb629205d026a6d4dc73a0f44ad",
          "sha256": "af9541f820f40257fda18c973ccf8c8892ab042e3a006f94ad55d2ce23301cd0",
          "sha1": "cdb9043f3adcc5cd7e1fc42c7d8d54d5238a247d",
          "md5": "547425d9bf7b62278b362df02ca6519c"
        }
      ]
    }
  ]
}
