{
  "formatVersion": "1.1",
  "component": {
    "group": "bar.prunes",
    "module": "transceiver",
    "version": "0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "transceiver-0.8.jar",
          "url": "transceiver-0.8.jar",
          "size": 28126,
          "sha512": "30c645bcbaabb750bf7b8511f413c01230f7cadb1de4b6c294e8f80c7b0893d47f8e580f5918f7379937475bb1b2494cff81e4f7a1a6b2d7dd28b4de0c4fe7d0",
          "sha256": "069476fdc73a66feb14b50573b1a434258dffb19632757f520278a882bba2310",
          "sha1": "3b26898e67a45a1e5c8d66f17c07744a3f2e35eb",
          "md5": "f3dfadb14846b49851c3a383e573a8a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "transceiver-0.8.jar",
          "url": "transceiver-0.8.jar",
          "size": 28126,
          "sha512": "30c645bcbaabb750bf7b8511f413c01230f7cadb1de4b6c294e8f80c7b0893d47f8e580f5918f7379937475bb1b2494cff81e4f7a1a6b2d7dd28b4de0c4fe7d0",
          "sha256": "069476fdc73a66feb14b50573b1a434258dffb19632757f520278a882bba2310",
          "sha1": "3b26898e67a45a1e5c8d66f17c07744a3f2e35eb",
          "md5": "f3dfadb14846b49851c3a383e573a8a2"
        }
      ]
    }
  ]
}
