{
  "formatVersion": "1.1",
  "component": {
    "group": "org.prunes",
    "module": "transceiver",
    "version": "0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "transceiver-0.3-SNAPSHOT.jar",
          "url": "transceiver-0.3-SNAPSHOT.jar",
          "size": 20346,
          "sha512": "aa7c83e5940df2564951ad54eea4b0e3d00df0763a3eb5a1a94569387e03d5365bcee9dc5b0d36d91a17109b5cadc9944bb2aade600d5baeb57f47aa95200b73",
          "sha256": "10061c89bffe2a92c7ec861b0ca953236f348bba47a72d5cac3319f22f725032",
          "sha1": "be15df924474863a6b60d9fa0e91b00872890321",
          "md5": "d99bce046a0a47551527472308788c9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.35"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "transceiver-0.3-SNAPSHOT.jar",
          "url": "transceiver-0.3-SNAPSHOT.jar",
          "size": 20346,
          "sha512": "aa7c83e5940df2564951ad54eea4b0e3d00df0763a3eb5a1a94569387e03d5365bcee9dc5b0d36d91a17109b5cadc9944bb2aade600d5baeb57f47aa95200b73",
          "sha256": "10061c89bffe2a92c7ec861b0ca953236f348bba47a72d5cac3319f22f725032",
          "sha1": "be15df924474863a6b60d9fa0e91b00872890321",
          "md5": "d99bce046a0a47551527472308788c9b"
        }
      ]
    }
  ]
}
