{
  "formatVersion": "1.1",
  "component": {
    "group": "bar.prunes",
    "module": "transceiver",
    "version": "0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "transceiver-0.9.jar",
          "url": "transceiver-0.9.jar",
          "size": 26092,
          "sha512": "78a02d70edbf6577650cb3d8bc0d9ff365a51fdfd280cbc0b3551677aa689b160fd7ca1c1905c740e7e82d5e186584d65154ce840ef7bce7b567f84c9e2a01db",
          "sha256": "a38261536ebfaa3bc2b5124efbf313cf1cf716b4d2690052c6f35373c3321ee4",
          "sha1": "752b1735e3a584e9b719f912994b0757b1f8b759",
          "md5": "e6d2eea1c1c8e1c6df96bc19cf2174d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "transceiver-0.9.jar",
          "url": "transceiver-0.9.jar",
          "size": 26092,
          "sha512": "78a02d70edbf6577650cb3d8bc0d9ff365a51fdfd280cbc0b3551677aa689b160fd7ca1c1905c740e7e82d5e186584d65154ce840ef7bce7b567f84c9e2a01db",
          "sha256": "a38261536ebfaa3bc2b5124efbf313cf1cf716b4d2690052c6f35373c3321ee4",
          "sha1": "752b1735e3a584e9b719f912994b0757b1f8b759",
          "md5": "e6d2eea1c1c8e1c6df96bc19cf2174d2"
        }
      ]
    }
  ]
}
