{
  "formatVersion": "1.1",
  "component": {
    "group": "bar.prunes",
    "module": "transceiver",
    "version": "0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "transceiver-0.9.jar",
          "url": "transceiver-0.9.jar",
          "size": 26039,
          "sha512": "79de6097581dee3e14e6df97be6b59a30db4470e888fb6c54a4755b80b5730ac77dbc21840cceb0935d685a9b7835ad3004c1fcb67ecf661a327f122546221bf",
          "sha256": "882231cd7bb3f7d48dfd0fb9635feca096dc74ffa3d623dc26a9b015ce7b7e50",
          "sha1": "22ace065e81699b5d566a3c5233483ff36ecc605",
          "md5": "159132ef3e73a3b2e2758b9e456c8390"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "transceiver-0.9.jar",
          "url": "transceiver-0.9.jar",
          "size": 26039,
          "sha512": "79de6097581dee3e14e6df97be6b59a30db4470e888fb6c54a4755b80b5730ac77dbc21840cceb0935d685a9b7835ad3004c1fcb67ecf661a327f122546221bf",
          "sha256": "882231cd7bb3f7d48dfd0fb9635feca096dc74ffa3d623dc26a9b015ce7b7e50",
          "sha1": "22ace065e81699b5d566a3c5233483ff36ecc605",
          "md5": "159132ef3e73a3b2e2758b9e456c8390"
        }
      ]
    }
  ]
}
