{
  "formatVersion": "1.1",
  "component": {
    "group": "bar.prunes",
    "module": "transceiver",
    "version": "0.91",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "transceiver-0.91.jar",
          "url": "transceiver-0.91.jar",
          "size": 26398,
          "sha512": "8a9c99607572fa1040b1c9fe070a5f4e14ca37726afca1141d47418deb74ef82640ef03423ac9d770d7727313c51c9842b32c7ef5cb9267f0a34b911c6894131",
          "sha256": "65d99a5d00fcb9f43411fb9b7066d2e68f22440c0f2a791ecc3eb52806bf551f",
          "sha1": "0842a5be80cce2862406478642d51e55afa61b35",
          "md5": "f378e3f30937f33d36d633ef5d05fdc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "transceiver-0.91.jar",
          "url": "transceiver-0.91.jar",
          "size": 26398,
          "sha512": "8a9c99607572fa1040b1c9fe070a5f4e14ca37726afca1141d47418deb74ef82640ef03423ac9d770d7727313c51c9842b32c7ef5cb9267f0a34b911c6894131",
          "sha256": "65d99a5d00fcb9f43411fb9b7066d2e68f22440c0f2a791ecc3eb52806bf551f",
          "sha1": "0842a5be80cce2862406478642d51e55afa61b35",
          "md5": "f378e3f30937f33d36d633ef5d05fdc3"
        }
      ]
    }
  ]
}
